api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
    #  middlewares: # uncomment if using CrowdSec - see my video
    #    - crowdsec-bouncer@file
      redirections:
        entrypoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      middlewares: # uncomment if using CrowdSec - see my video
        - crowdsec@file
  # tcp:
   # address: ":10000"
  # apis:
   # address: ":33073"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yaml # example provided gives A+ rating https://www.ssllabs.com/ssltest/
certificatesResolvers:
  cloudflare:
    acme:
      # caServer: https://acme-v02.api.letsencrypt.org/directory # production (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging (testing)
      email: admin@domain # Cloudflare email (or other provider)
      storage: acme.json
      dnsChallenge:
        provider: cloudflare # change as required
        # disablePropagationCheck: true # Some people using Cloudflare note this can solve DNS propagation issues.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

experimental:
  plugins:
    crowdsec:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.1      

log:
  level: "INFO"
  format: "json"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  filters:
    statusCodes:
      - "200-299"  # Success codes
      - "400-499"  # Client errors
      - "500-599"  # Server errors
    retryAttempts: true
    minDuration: "100ms"  # Increased to focus on slower requests
  bufferingSize: 100      # Add buffering for better performance
  fields:
    defaultMode: drop     # Start with dropping all fields
    names:
      ClientAddr: keep # Keep client address for IP tracking
      ClientHost: keep  # Keep client host for IP tracking
      RequestMethod: keep # Keep request method for tracking
      RequestPath: keep # Keep request path for tracking
      RequestProtocol: keep # Keep request protocol for tracking
      DownstreamStatus: keep # Keep downstream status for tracking
      DownstreamContentSize: keep # Keep downstream content size for tracking
      Duration: keep # Keep request duration for tracking
      ServiceName: keep # Keep service name for tracking
      StartUTC: keep # Keep start time for tracking
      TLSVersion: keep # Keep TLS version for tracking
      TLSCipher: keep # Keep TLS cipher for tracking
      RetryAttempts: keep # Keep retry attempts for tracking
    headers:
      defaultMode: drop # Start with dropping all headers
      names:
        User-Agent: keep # Keep user agent for tracking
        X-Real-Ip: keep # Keep real IP for tracking
        X-Forwarded-For: keep # Keep forwarded IP for tracking
        X-Forwarded-Proto: keep # Keep forwarded protocol for tracking
        Content-Type: keep # Keep content type for tracking
        Authorization: redact  # Redact sensitive information
        Cookie: redact        # Redact sensitive information
